Added linear regression method
mmcs-ruby/silicium pull request #118
Opened 2020-10-15 13:09 UTC by Outrociaocul

By gradient descent

2020-10-19 09:59 UTC, Wolwer1nE requested changes
We need tests and docs.

2020-10-20 09:48 UTC, Outrociaocul commented
Looks like I've done everything I had to

2020-10-27 07:21 UTC, Wolwer1nE approved these changes

2020-10-27 07:21 UTC, Wolwer1nE commented on lib/linear_regression.rb
> +theta0, theta1 = Silicium::LinearRegression::LinearRegressionByGradientDescent::generate_function(plot)
That is actually a test, but it is placed in the source file.

2020-10-27 07:21 UTC, merged